2020-05-16 00:30:00,992 ERROR: Exception on / [GET] [in /Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/routes.py", line 29, in index
    return render_template('index.html', title="Home", form=form, posts=posts)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hiddent_tag() }}
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'hiddent_tag'
2020-05-16 00:30:01,601 ERROR: Exception on / [GET] [in /Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/routes.py", line 29, in index
    return render_template('index.html', title="Home", form=form, posts=posts)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hiddent_tag() }}
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'hiddent_tag'
2020-05-16 00:30:17,756 ERROR: Exception on / [GET] [in /Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/routes.py", line 29, in index
    return render_template('index.html', title="Home", form=form, posts=posts)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/skvozio/.virtualenvs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'hiddent_tag'
2020-05-16 00:30:26,965 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 00:32:04,710 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 00:34:20,570 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 00:36:44,096 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 00:39:56,115 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 01:01:40,898 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
2020-05-16 01:13:00,713 INFO: Microblog startup [in /Users/skvozio/Documents/PERSONAL/Python/Projects/microblog/app/__init__.py:45]
